CREATE TABLE utenti( 
	idUtente INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	nome VARCHAR(255) NOT NULL, 
	cognome VARCHAR(255) NOT NULL, 
	email VARCHAR(255) NOT NULL UNIQUE, 
	password VARCHAR(255) NOT NULL, 
	imgProfilo TEXT
);

CREATE TABLE ruoli( 
	idRuolo INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	denominazione VARCHAR(64) NOT NULL 
); 

CREATE TABLE assegnazione(
	idAssegnazione INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ksRuolo INT NOT NULL,
	ksUtente INT NOT NULL,
	FOREIGN KEY(ksRuolo) REFERENCES Ruoli(idRuolo)
				ON UPDATE CASCADE
				ON DELETE CASCADE,
	FOREIGN KEY (ksUtente) REFERENCES Utenti(idUtente)
				ON UPDATE CASCADE
				ON DELETE CASCADE,
	UNIQUE(ksRuolo, ksUtente)
);
